[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "19407fa7cb8c658ddee6c46fbdb8825acb94edff"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "f4439988f6f38878492e75c107363d9a6116a05579ebfd4b77196af72f34e14d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c80f51e6be6340c1f1926944a90587b49c108974"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a536b4d1fc918b9e4ae478733e5aa1984d55efb543d2f05296e150ea302a1da7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea8eb930cf48fcf42f7593c29959d09b26634882"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3804c570c35610d7ed318d55ad5d15e7c815cf5ef8a2854b9b2257c219cb797c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6da7568e2da708c78f56bdc8b8cf3a1514282691"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "013ee050062f0c9928e57fdb4c7494bf4fd8d9de3fe6613a1fe7cb4a6de0777c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea14e66e1d6556f6b534e41305523e97511bcf51"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8562a8d98a932c68315d5439383a02b64b612afd95ba6f993bcfb0d69eb30d37"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c4a41ebf6ccca39d44e306f6e6060717a3a7068"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "99f32b4f9c1d39dcbc8fc6bfa01ef86e24b3c0bdbacf64154b89a4a67c5e0e36"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7c7eb3e7d5c7aa1533a720a885d1bfd7be37e24"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9024ac549cbfba4e08e5df6e748362ef08beabd2f4f536693d12fead12e724fe"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3cd6d64246062db54a2ededee72ac65fa8d49aa"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2e26945e681bce661e72c5cb9a830b166dadc6ace6af5a6cec2c9600932676ea"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "598e81a5215a16ce5f1c1b78e648862292583878"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "59bcc466eec3d568c095b0a1cf7612a2f502967c1b4a9eb1363670385db615f8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d49a79b3441cff0d17e991b9fc1acbdb06f64c0e"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2a3144fdf1b14bf56bf925006dd8fa6c169de8e587efc07aaf775098cc9fbdf6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64184a7e74292a3ffc3cb5736e162759b39d7356"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bfc651c28d2a346a6429cb1f1630907b8732fb81d27b21e7d7a500718f56a4c7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c20d7d24549a32bf3092b6508937bf2b878fd29"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "15248d7390c5eccf46376099b6ac762ea9e912289270a8bba60e38753604b403"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bec4ba7c8474b13eeae88c75baec39e7babbe515"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e542e16896963d9b0b3b2dd93c36846686a9773541b0ba7b8309c7eb6538099a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ec0aee51b1f8b979eb4526319fda49a8fca8373"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6c2cc046acc6fb1ad3e68c02c632df54049ecd05bff49d29fce73f82fbde610b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ffb487dbab8f571a8f15280417ffdfd705da15"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d71818582aa718bfecb09eb390ae2bc6cc410acbc730c4a2cb69f51a76213452"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcbf64ddde739351bce3297d19ebcec978e96009"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f1dc7f2154e9d68fe6e007d303adee01457103835380ddfe6bd07ff76488329b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b785d6eb6f40e8cd74e34d324143d8d0003b09dc"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8ba4694361da84c76ae6c2e2df549c40a9b8f9dcfc1da63abc6330b8602594ab"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a46842157357cddd62f8ba214150ef54d1fdffa"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "3a694ac9debae2f985ebd88955f88df00933b6bacfbb36342cfadc3b18430c50"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc065f359c17f8676440080bb13240b051bb4284"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "9fecbb40b3aaa9b31c4504998da512bdc217b8c0b9a0d2309e1eefaa3b72af57"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "261ef76d6bccfedd32860618ffca987247210eaa"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "794f1806ccacacd03e11ddb4c6e8f104f20c67f5abf062e1c62d447e9bd45d77"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "672cee3c14f6b06007dcd3e27fed7cd7bf48097e"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8d78b2949a210470d4c6d1e51c8f4f6fc7bc43f58e130f54c6bb2707c289ca6c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "fb9418a7ebe54331fedf461be7ca637313facae5"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "13be3d6f8881dce1c087d1fd671f767ae931ee715a272b00c902a19ade483822"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c420061a6612352adf9dc64297a5275e80230ba"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c413f5d0569773b654e89eef261f05ec23d56715062e559a440c648f02fe709b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d95dd582d209fe8d13876d9f07de318bb9010810"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3a7270c56eeae4b841ec7401f9bbf82b7c02342bb29973fd2c67d7af61a52138"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-gnu-cxx03-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c108a15c629cfb0f0e52df47a428c1b3f8565cbc"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9b24c55e77e05f753b57441dd184facc7031ac32f6a02a88ede1900ea1cc419a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de993d6a30f34c41a713276373eb5b54fbc0c160"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bee0387ea264cf82f8f9ebc8930a22f1fc50f842a02aeed03c302a8ab5b9d8ca"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-gnu-cxx11-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12418df720f5c6bef8684fc21ac42c8457770a96"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8ecb952e3ca21f6caba4b597b3d3d7f6b60f48cd07efc8796dce539a3f6fd35b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f952c0794231e97c4e6dfd57c8a9c2cb968f52f9"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "432179e306661f543392740ab4747260b14974527e0b22b120b8008cbee07daf"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "37d951f2c5d193a7f5333d1483b1d2e6f2b7a770"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "fd94aeb998ce7c5c3a9c002751d06edbb9603ece8ee9ec5d80b44dd54cb4e74c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf89d3c7414a919faf6488bed14332b0a003007a"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "84f1dd2ebbbcbad33e0b493dcb62969d7bc7376f991b919e980f0d70f28d79bf"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aba4d33414e492b27f96c7df258d8cc91f48ed11"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "ab335e904ca13dd3cf4c2055f2190d688c8b3190fa9512f5a54caeab9d938557"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.2+0/XGBoost.v1.7.2.x86_64-w64-mingw32-cxx11.tar.gz"
