[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82441830ab4a99b5a39ce2e6c569d9ffc2f2adca"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1b9c9e890568aba71e29e627ae349f1feeace6e99479b39007fadc734ac866ab"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a73753a2ceadc8a4614d0b58f280768d5a526d94"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bd8cf862d269b4f2226560a21fcd3804466bf94770e1c4af8176913783995af3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da1e9993031b9de0be8389a249c20b70292a912a"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "530c95ae7f49daa3974b4f3d2ca3f6d7d09098df9df122e9c4f1c47acc4fc5f6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dca04ff53f63fe2c1dc9f268945a45f8436871df"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "fcbffb359190ae99bedde62254c09caf6fa0c8beec1f4f3385b87a9eae3c2af5"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40327a88859ce9506d311631d7fd1f384c1ffe2f"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cac1d7fb34106da65c26dbef225c63df8c02ae4d144d194360168f8bc0e10ffb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65d0730d0927e98b39a4cec2816f02d319f746b5"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6eb889e43244ea087d546993bf3820def6a34f511522feecec3b65e063cbb67a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f45542fad4b0794a3ae240d8055205b45674020"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8b036a3d3ed1af9625c6e8efa4a33f681eab70602632a3387e8cb47600e2d75b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "040a22663b8ca77de40333880d9fb787d886d0be"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4798dcbf0ffaee6ac59d90c45a0a207176a9fd1c9a674ffe8cd26b2872fa37f1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f8c33c25062ccac379c42e8f568d72b997f2697"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "44bc19845f8747674ac37f42f7b49730819a1062164030cb1941319673493fba"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f9dc49f639155ed787b203acc5bb28108f85fe9"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "650e7fae172ce776f22a51e79c335e25bb271c4adb33257b666f25e0da9b90ca"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8b4b35d75a4e6a5f9cff730f9a71590235f096f"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c29b987302a9448c628d102fff94f1b4b251178d97c6076f2d4e2f5e357a6a61"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7878e6ab1ded17492213765a5887739f696faf8e"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c769bee56d589f8c23951528b9576f16ee6d89773f7e92b9035ece7eebe4005c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfc8a62b2571f78b904bdca865d917bfa89f18c2"
os = "windows"

    [[XGBoost.download]]
    sha256 = "f9a4235f974843d0e7a083c482c87d5b6670dcef59a44ff2796c354f8b0ac386"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d0803394f450ce0a31ae226e65b6e3f036688b8"
os = "windows"

    [[XGBoost.download]]
    sha256 = "9f29a79cea737c51d62d1b1eb8f73d08df454f6cc44f955a1faa348ae271ce79"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "622cc19466c2abe81bec149bb3f4a2a9ea0e5d73"
os = "macos"

    [[XGBoost.download]]
    sha256 = "c6fae91f6a46d239817a3ba29a2bf963f96bae4dc95bd2e8fb211783b3317393"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ceefbf9bb834487c2bc247327ef488e95b1db90a"
os = "macos"

    [[XGBoost.download]]
    sha256 = "d518860f8d8cba989b4d7fecf7061b913ea97b33c38c6f0ccd112ca2ef2b2b87"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71de0fde8e8dd6d7d67078f3182997469d1067ce"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "04ae3fc137475298d7a35f1bc451eb31d07e63632205275f1b48b5bd56c834a1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51760a35c00d03a1b2ee373a49af64d08700a64a"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "910a0a5e4ceee0c79be3ce92c3a0b5551aa6cf6ba6c0a861bacd9edda327d226"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7488f19012098a17d08cecf0b7fa25d509dadac"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b538493dec2878467a5c43578dc8407586540ff1bf3ca99773510a3ba46e1d91"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84554e79cd22857d9bf1548db2925047cd7def3c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "52da687c995171acaac40770ecf6f0b5fa4c837040255a84d02e669ceaece165"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "615dc3ba60a68a98aecc1ab1e5fca84765640c30"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "74037a4702eca92ce637c23a6d2bd8c73bb4f0aad0dd3d00b1384c8b73fe34a9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f913f3dac6906bab5b556baf4be13947dad3eb3"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "7023dc01684fb68a9554e0fa69288351af57f49415ad7f3aaf9f602fae570b7a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d8aa39e5ddb88833022de9e988cd1ca73b58070"
os = "windows"

    [[XGBoost.download]]
    sha256 = "dd2733703e73fda8ea880121e06d201188c181241c9e1d879216ff8c6bc86983"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "185e446e64ed898aefdc7361bbae40030fef5ca9"
os = "windows"

    [[XGBoost.download]]
    sha256 = "b605f1da9216df35da73bf3f5f07dc81e6e208bfe8df172beb8cb869c5cf7a06"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.2.0+0/XGBoost.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
