[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "189df733838a75bb863181a0b85b69e8e331bdc7"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "54c71b50fb24a59d5c479a789f5dd2935e41b2076c1fba23849730de832d14a3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb5c18f90940a10a24b32991bbe077c763ea6f0f"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d273bc1d4031c27565ecf233e4c1b172a168d4f28b90dff1eb9b9177d6520442"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8675d4faeec15afdfe6c15798d4fa669021a3399"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "05f9a51d6bbee9a83836728a9832a40e4a1f810c56854041309ad9d86c63b7ee"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f725d5324f9261c25df84ae1603d6c3862ee0c0e"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "01759cf4f1cb8913b782792628d55d507ed41ba4b7da44476f32e6cf617d7f0b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9243b428dadebd054d764b711d03f72f4041b933"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d5b54f953cddffad34214313c21aa5dc28daa39df6af44aecd80831d3c47c0ff"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d79ca4f8ed762c726545d4651f4e4596345c27e"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c84ac068498a4b381c572064e84dbbd21b4c372186293a5ac64d3368965220d3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dad38b1221db51c4cfe90afecd36a8fa6fa3baf"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8decf95625492a7d6b8e6444adf80fc3ace04c60b7372ab138d8b1f6be1cd425"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bbd1d458ceb5b727a8ce0a621d847c226d67e72"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2b76af15d83d2f43e02fa3355806fa6e4325124db383c751f59686272a2d1ebb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "338a847ee1a1a33340362827fd3cf818eca323bd"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0fac124f0ac4b42edeb70d5175445f127529fddfc67c6452d5bd03045077079c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cc2952c2905c2b319e8e0561135bd08fe404db5"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "51babb48cd39ee7ce0368bae72ff8a1a92517f95967372efca54953bed2e7845"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ece4f04abae064ad4185a0dd588bf8bd89d0eb4"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "568c5ddfa0ed1529c18880c795fe956ea81e9df74d4d92ec2f43cdca105a92ae"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b490d5fadbe94db74bd3ede86a27a458ab9d8da"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "43ba7561f2cac2c17d57feb59c1786a341480f925335a5d49625193e9cb9578c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd29ebe55fdca30e6983f5ec1b5fb559f5bca0f0"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a84dbd3dd929b9a1fc810f5833f32fe1b4336eca49d84248c14cdfeac489d0fa"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c4ddde25e51f94cf92fa6f3d11914babf0c365b"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d741c507484dc87f740c642bd991e95599a488483480f8d634759b4c8c34c20f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c7a47307f123bd5f56bedf73be37a4f0fdc7ee3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "591262db8c99ded9fe133bf42ca42c5948e702932628d2943bda57a233f5e726"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3a509e29906516e24bb0925ff002789bab06792"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "58a5671a739d1f89795581359d3c5bf13b24508472c3439eeecf8d6a6caec573"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6e9a77d8678d10746cd5ea2ac231aa323a2e958"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "03af8998d6f820e20c029ed3158cd65fd9728cdc8ebd65a0d59393c6250f76f9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a660d241c0bc2da9420a35a23aa99e264b008fd"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "d3b8bc679849b5cf54cad6e317e77bce6463037f84ad50ff72a40a77bb0f27b4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfffa4a6369d2987940772559ae9415b82e6abbf"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "0d98aea47c4a51bbe14ce7188975f4f4565f3c87da6328f1907f9bde1e707a26"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a0afd16f5d42ca05af49e209fe102c2d805a94a"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3e45c751e64f0d1ffeaa711503a7afa70c51aca528c822f25d66ada148bb1924"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5691d2456292e6fa2f1caf60673cf053a041f951"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6a7fb302b5fee110da808ec5c567f8dce8820969ab0acb08cb967238801c9f0a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "04d6f641a3148df077532d6f033686c6d47d36d3"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "3a478e1d61c6e26cd643584c710e0870147630b9cf65191bcb49dcd61e431923"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7eb698a7ab5576e85e87241ce9758169dc08857"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "eb7b0559981ba0016ec92bbf9749b0d5ce0b3e44a9c2318077ac0c055fe94f74"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a0e3c6bac509298e145586320ad10bea13667d2"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "032172a40fe84d5e9fb8f969b1529af082e15e32adcdf2d5bc0433d49ab0931a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-gnu-cxx03-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52915e0d30bfc023938d608200c0496c90991437"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d348aba2bf3cb2a21354179a970dc918bb249528d098d31c45fa94b729533f04"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b3d2a86cd8263ca85962e2e2b895ee49a96a778"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2abac4de6d558e57466e660dbe7047d500da91d0e3d6ba3effdc8edde0958066"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-gnu-cxx11-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43e42e880d646750ea665ff47ca1e20d5b7aab07"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d7db5eee34a95e538f6129ab3385b140caefe6cf6b67b98c74545ef181d796eb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42805cfa3807a9d040d1a3aa2bbb4e3dfc590ed2"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "38e58ed55fc894842a55490519ed4a7998cb9a7337a7f945a1c5074c78b1b25d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "8f945350a31dec2031d94e2a511ca4952b58ea75"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "26c9cd36ec93c6cfdbfff5109c6cdbc658d17f08408da73e10b3088a939e190e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a39cb14df925f5e3f8efb74450c71ee4a56fd756"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "eb50ec1ea2cc84d2a2382bd968ba3e2f3dd71e2ff59c9864ae37169dd020e1ec"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "488f406ad4458f873d0b15cccf78ff594459373a"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "848a0ea1ac2b47f48b431ab173c6a225e9ec22daaa9bbab4cff32a2f2281ea51"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.1+1/XGBoost.v1.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
