[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "665a89dbebc976d2ef643a9c44495603a8b12182"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "62a5bc98126386560c7cd99e8cbdcbf920972c3c539b0bbd66ef584facd7a56e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3717b57cd45b5be4af00fa182948d6c6e984380"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "523458ca29ebd7130ac8c50c9f4de78335dc55a7bfa59d9d863258be71498c29"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d17b6db504439be2994dffd3504296796597040"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c6100442f087a8a057daf72442f808542a3b8051960f4c7e81813d56f906e2ac"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d77b5f78b6d00f1421a780be53272255b8de2cb"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ec7928e85cffee40f348fa14cf5ebd2f578a832e6e2c2072e19176aca82a0aaa"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b98a812050747b074482a828364affdb7fcc8eec"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "52bd1d4910316a65a471274f2baa56fa3fca6e9c28adad18cc491b6c7642a8cc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8eac011f48c3d341020a7e620a8c7a91e66048cd"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "83232d0baec2c754d2b7ac84f064afaa9161236dce7b22b7cedb12ee8507551f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3f4961cafff15c3039533f92e405d1cb8bb97d1"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4a1d048121c0179b57a197be0a130d2fddfc3346a07a0f2224ef967adfcd8359"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8677fadf77dd1d53274c54d340756a9b8076cf8a"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f89aaff35d66a03bb2c9b1ea4931c98d99709df8dd16f0fc849faa2078864aad"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "830af5dc9455af80a1de44fedd184552fa70d6dc"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6f66200e52e1d2bb9c3dd91d9a5ee798f71dd4b561ca8dae4af2cb1cb2de9e34"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a0a403d070ee666b3cc555ae3277e78608dd7e2"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9adb742c16b770b7eb818356b7532d20d358ad501c73ba7c239a01bf6cbef6e2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e075a049e6a106bbefd1947735485e278795406d"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "dd7845a0e052d2117ef7eae9c96bbd3d800608be0d993ca3a134274225ce98b5"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "042b2802c4a2106ef27daab8a19c7cd31f6c8477"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "999267f5e7e69a82b08b50311de684a3e20743cc85e51bb0c050ed9471e6fdfb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44a0281a838c08ade10aa851bb629484d9bc93e3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "84ba6fe91e8ebb5fefc12648d5547eedf5579a90f50b04ebb302edc02f1d3cad"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx03-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973327f4cbbad34c90ad9426169b067704cd9418"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "adf2493bf6ee9a35597366759fd81ff1e44089a0eab6dc92f516092238d66484"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59545c97dff31442b629f5565f4c580658f02d16"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bd8a53c7f6783771881441321daa745ff3bcdd4c86ed6f883a6708e7b71bdf32"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "758e015b1fd03a486c6c980c057b98d6e9423ed4"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "681bbe7fa339c1d415f06c153ee2ea2589279734362d70b8937e42e2cd65ea2a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d2eff012afe6d9874b06888bfd242a883a124b3"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0ac634b891f75f22b8de9057895bd27bd6e52a8d304be0cb70ea44c70668645a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ec3e6f06f9b53dc8ec4f38a356af2870647475d"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e1cb890b27da0d3832f03bc8a0565cdef2e56a1c64c92856931946354a03e0f2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54be901da36dd500f027a51bd4e6a7ed8c7dbc95"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "812ca14cb84e472e0e8e7005640a59e8f13cd86c5e6ad9c5aeb173364f1afc97"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e85196a18d17fc8253875c8b6ceaf094097f86ce"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2826f1b6d7059445fdfbe69192c32b03f34b2f1009cc7a4f817096b5936cc435"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "183888825893b61e45853d3232c8f9119ab3ce93"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "bdfa80a9987ddf9a5374d96a24b2a3ab77c117faefee5a98293b56da34d28603"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "bc8a3bade45dc3b54d2afa090ea4ea2613fb578c"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "7f810f2d53530e591c2c456c56c9f9e78a778d63b2332b51e6d31508854d7034"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "d32b5283bd5acf0bc418078e497b111e79092076"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "75cbc5bcfc2030f5d9e9d3bc307e095550c21b3ef13620be41e51a3d348b3531"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d1ae7b23070fb29b47a589f0812d056c85523c7"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "be3a106f1584b671f205c329129833b63f4c98b5674c89773e95ebe08811ed4d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e9b261ed0ed711feac1804236eeb6d33f9ec792"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "ce2468d748c2830de76aecb8668a897249c6fd1fb9e3c69ee38f46dd3dd64ccf"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85b543f116dbb885ee89d737c25923ea37b81181"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "c2de3b8f471ec35d7f1f98b5cc2aaf29fba2bb14bea204f2ccf14d72f5130c56"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c35e9bc98c79a020363ece62ba6d8cba57442968"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "f6c5fdd6528cb7cd3800f492b86c125cbd09feb15d9fb11be86bd8ac688547b2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2baa3c41eab7f0e63dcf2af06fa76c6ccf8a72cd"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f155a4da6b956ec5a95a84dbf18cbd4a46037bed3494a7f9d5ae9a78eb4bcb75"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx03-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de269f33b47adb1faa9a27d21178288bc60148c4"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d22d001b1207490b71db76bacac7a041f8fc351240d921896dcc9bc0c854a6f3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx11-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "872a03d60e1d9d86aa79809f08ed5b08ccf09ed5"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "30aa03469ba2afc1b591ff339d3a201de07ded5d042024d3331f5f828ef636cc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx03-cuda+12.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1434a34a5bf3af19e09c1fbcd087e39b293b7b3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "11e4b3e3a4371298b282b206194ab2a128519c16aeedf25ba4299aed59625625"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.6+0/XGBoost.v1.7.6.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
