[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04f54bd351b2cfa62937ba9c071949aa0122dc7c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "834454752e6e29906c822bf684b1e636f056cc2fb817de07afad6a9532c918d6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01b9ba8c1796bf7a642ebb7e335a398634816d26"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f29f9620f530e3144eaee96a6c87871c5997ff2b9280ccc5d96663a63b991a1a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6dd4c81a45175bc2e54925e592d40c2e2ebde19a"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "264b2a5ecae66e96d561d6d4ef65e19c0eb3775db7a5e999d2a27677b4802676"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce88b78aec57d42f5ede792c6ad0dee42746b028"
os = "windows"

    [[XGBoost.download]]
    sha256 = "28c0e2e829d91bb0a4976399b00b76b6140d5d3e5839bb0617bf81baac0ad187"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8024923359ae1121fa3eabe8b21d113449bff8b"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cd67bcbf0002e5587f3baffa9febf6d7e1b23b9a372a194d7254a9212b66c7bc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d0a09ab3d3e77c0318928d116516b5207228d74"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1cbca56523af40ae7006d094828dde46d0c94abe4cf7651538f30226f60681ba"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60a10622b0b72f6bba4bf29d0cae17955d82f196"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a61ab58c011e406340d7a6da00809fd0642971f27098fc1a3bb9e7772b252a80"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aefeeb7e218226282d76837d9c7032efa79d7dab"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f917926cc305679f86671860f01a6fdc23a0f4d6f49692628070400c281455a6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "238ea5a646b3f29b40075f22ebf64e8601813cd3"
os = "macos"

    [[XGBoost.download]]
    sha256 = "5e0bd3bde0cff3ac873ef92290240e0ef224f8a0915400166d715c1b33302765"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58b48bf606fa3ede7529755d61088c06b0544400"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "818748c817c2abb82063c1a50952022cb6777994ce4008a30ae7ac92a4cdec2f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bf187400151eb9affcc6b266ab5014587c97798"
os = "windows"

    [[XGBoost.download]]
    sha256 = "171cdc0a9105f4da557193b1032f01d11c34507206aaaf5f25755d2bccfa4158"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fde0d928029495312c44a7169c911ec6f731a419"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "21e99b731b0e7bc85646d2a54a6e98a570c0beab479a43a631657cedcdca8152"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bb0f12255a9f4c6dcf79ccde927c78e415d56d3"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d0fb8e35fee92965ec48b4eec81b4071a5fc18eb6ae4d1288fc1e63bff916051"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7939687cb47aaa37c53ea4a6d3ca8bc001d5df77"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f9a9a0b045c4a35a3657c41325c49bee1f19cfc1f5db4ad6d5e9be59961b1207"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8b7b03ac9c9b4111382f743847daf6f5dc12461"
os = "macos"

    [[XGBoost.download]]
    sha256 = "2a07399e8862a5f098602bfa477c6e5f2d6981abe46a63ad9fb70fec0f649814"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de70cbfb92cc0a520d49f36169635cb1cc77b3a"
os = "windows"

    [[XGBoost.download]]
    sha256 = "67b29746d15bc0781f49a17be03354de361d460f868b483ba081602eb858e892"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d5712770bfaeecc43b8a70094ebdf937bd9d67e"
os = "windows"

    [[XGBoost.download]]
    sha256 = "2f685b7cb381ae7a90a3dea7f39f0d895f9859ba9ad5c02ca3bdc90ddf79c8ac"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9244560f99d22f9b6c932fb05152c4ac13946ebf"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4b047c7983c3267d632787fe325729ad09e4ef14fa7fbe70384fc9b4c4ef2e78"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "891bf21f509cb85a6d09c893f1496b8102106783"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ef18bd8c8ae301d228813c43fc0859055d9ba48d0b33795972a2ffb40d3791a9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd940f94b0ee8812c3b44401418e6e8178213a20"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "170c1be26650364db0832f25f617dbb28d395d95571be5fe6d55e57b9fd11ddd"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b47ac4a5efe3a3e39b9269df63c5bfd129248176"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ab578a45135a6bd949052f911b33870f68a4331593720bbd7b58993aa5eb9382"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6646a0ebdf57e13ca11b203237ed8205e3862ef"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "72c08fffa7d96da6908960556ee447a73437c5f0df815de083577ede581b0d0f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v0.82.0+2/XGBoost.v0.82.0.i686-linux-musl-cxx03.tar.gz"
