[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b548d0cf2acb85cd459d1ab1c3e8d7bb952a705"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2376e03fa0f8dd4fe156a357cdbe1b0b79a010c87b8314aa3f7221080f84a81b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19a27baf46229ddb44869c5d8b7f8c09e2348928"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b2f4cd15f72f7c08d4b63cae1ee0c15f5339b4b0bdfbec74e0137a5d6c556fc6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71955683c903554dd88fa6a8bbf508bbbe02327c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a6ff4e84425be15041d5bce34cc227280ea715fb4f24d85769b9e33bb890d047"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "456da9040953c3bf95c3dc53907b66a47fda5a51"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4dd4105e7d3fee559ed3487a9bb08efbab08bc12e918fad5cb2c4134e82ec480"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a2f0e4390d20ac1f9997b666d86ad2441ba267f"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5c43b15d210902d00a14169540a7ff1df02d5126a55936b1e5eb25506c0ad4fe"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b43fa189a13ec511d82cd61bf833780bed8148ef"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "eb5b52a16768647d3ef8637c2d195ef200b3adf491488698eabd150e841ce107"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84327f96478f6bc2ae1a188aa65121ddd4132013"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "78080cc700a9882153628e57429c7c4fd7d7c26f1bb14055ba94332af77c8ff6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c49834090b236affb1b6ed983be558be987d4dc"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2cd224b14b5e1a75b68845e095ebe645e2ce55a0f1c91de618771231ea772b45"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a5af113d82bf07e81f6e73a48b31cc0f37ad77"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f0182877e4972bec0f927f7af2431ce9cc1dd2984aa1f4a0e903ad5a07d85470"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "801639ab243623ba0354f66dbeb02c3004eb1646"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b70aa52597e8ed67e687312f7a6fd774d3a737b20a78915e6002cb7f91026cc6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7028fb94341f01ea5e0c6ebc92308e5dfe3ce627"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cf1badddc43d00bda4b8002bdd517c605199fd653a22bc27dfa2e7dbb9a46561"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4718ced342144c6fec575604488d08d4aef37b0b"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2bce4dc61a7d9d1aa1aa74940e4eaa7137eec67ef08515b04a432165ca6dfb8e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae48d624214536c70725273b397fc730af9d1dd0"
os = "windows"

    [[XGBoost.download]]
    sha256 = "83494c908c3cebd5dbdd541a25bfc371cc937efbc0698a38a07edb46fddd9eb9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f4116cb395dd00a20c64e9284852f1fa2873d03"
os = "windows"

    [[XGBoost.download]]
    sha256 = "5f3d8e1c07d6a66860a4c964da84220cf1633404d23d3048f5439b8d94c8a3fd"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5978412bcb99b0281849d42adbe684973ff1a0de"
os = "macos"

    [[XGBoost.download]]
    sha256 = "a20d7e1a481fa2a641b046d02730f38b4145d4e1e58d99ed162c99c72d36f546"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acb5eb25bdf2eb4e4b1f7f7cf919b90134c238bc"
os = "macos"

    [[XGBoost.download]]
    sha256 = "d57c24f1b142f931789ef8321b392af6dc58d747b48b98dea86764f3c555d879"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c91b711fba325a05e3d82c1f21c21378e271826f"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "85cd74fa3db4da4d684277a2d52d1d533b91987a9be2bde61ec4dedc22d75b8c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ab5b37c11e04ae8633d736aeb019c71ecebf7a9"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2d23217b6f30339e1bab63b4ae808b35225435314fcffb955642d8cc2f23507e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77fe0048897725c2ea1e6cd7711f1b33b4aaf492"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "55963e71d0611ba65c8cf8de8651a99af11480ffb7960de2955b6956d634973d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd623ef46c3086f95cfa520efdc352d361873637"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c5d7ebdb8af7006b32ef178272de610ad628f90c3b9a775487c5ea1ecc4924fc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4e7f8fd2296bfe57ddc7e50df0cae56e58de017"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "153268ae1ab6b76743781bd4ce745129bcc1735c4477d8d5f8fa21ea664e891f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92fb75bc064823f51270fc988360a8b80fdc8513"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "2ceb7c74c57f023e4d3861fd6d3dd11739707c007e7a814f3c4cd4c0105272a1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4443930925f4a45951f3b1edbf1d37d4c5354200"
os = "windows"

    [[XGBoost.download]]
    sha256 = "1419132b9db32efcafd7ee5f2b3c3f63f23fbfeb18701b895a14aedda706b18a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b4a2310d39c3e7c676f8b0faa050ea4b3b0c14b"
os = "windows"

    [[XGBoost.download]]
    sha256 = "7224634800f1479d1c97edd61b98d7debce3830158e2bcc1207dbf4f6f74d988"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.1+0/XGBoost.v1.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
