[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "6ff2f0328931ee0d12c34497c342382f40a56a39"
os = "macos"

    [[XGBoost.download]]
    sha256 = "3a9daa0478e7c2ef5298968a2e2c5ca166d43db26b7b711349d69bcf4632328d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5ae8a860b43bbe5ca4dc348c2af05c43a901625"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "661f78fd241d02dea07256b1e9a115a8cb5a982578858f36175c9acde353f6d1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc4f7618c8ebbcb88fa4adaa86c2ca9b1ada96ad"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "67509449fbd7e8aa74298e711b422bc1dd26816d2cbe727b274388bf034a4d68"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cec8c1215b716abd9c2c816e5aae6d0223e44db"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "10841382b4c99cc89f6881058c36ddf6253fef6e097aca19b86bca828cafe4d9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c2e782914680b6a010b8b8f9742d51d9dddf5da"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b69c37b109d3ccc9c4cac47f8c610c53153acd318b3253462ebe9842d1cee3e4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eedeabe4ba295aa83ee965c1b26b0d9be2475b41"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "7bede845a6b69c67420265887d586f3aea13dd07816ec7b01b24b8ecc3f93b03"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08a0f385ce2a43645e623746cf57f9ac8d4d2f3e"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "41d20512437d83807743cd3028fcce0cfd35154be2cf1072666388e31a5f5409"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42e9a65df707c5fbc9c35693b8c287946fe9d1d8"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5aed3952abaaa1137270f59d8df7a871c7b39116cb8c9f075dec82e9bf4d1e8c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74426b72b350e4de9b4e9120b7a271a083968695"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "43172ecad70dcc5333cadf472e6fc76f9b3005a9364d888dd81e12ca438f7546"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c94b1b32ebb0a404dde5bf388925976433e2568"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6a3a9d65e0144afc25957cc12c80eca8ef29438fef523b6630db3fa915d05d2d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a39e24d179a373b0261d6d8826c11d68f2407ca"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3c6a44f351283ab9aa4e90bb02e9ab1471b73dbffc56b32d9f92e4e8fd531eee"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3392bab7a8a08c3bf6caa63c6c2d1d8fea81975"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8cd936c7101e41ad89abe93f86aecca316e4386ab1986fd3aea99b5a6bf1b077"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c96ed630624dc040ebaab1a35a5618d645a32b93"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "721366598150858caad6337c54fb38005b5718d4e66814f7f1e6a422d3602a95"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f24b497c2f8c8243a9af86927a6537f47ec1163"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "490174174cebaad4f4fc136f2cbeeb2641457df38a6d80d0c2c477eae7a57d35"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2470f286ebbed76783162587a3633caeba79c9af"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1f0849b881c37c35ebab17700fdfbc099366324fde4d7b21b81b142f56db830c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2367b3d4f93f1759b211689c2bf803240b9aa059"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "522fd51d5838e7fd89e925ee2e8b7e9d289fc1bd8cb3e80c703bb063de3335f4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5c7760141a466517a423f4886c209122d1f3b0a"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f1fe0c727272b3e457b2392eaeac00c182b6e2423d61c0137d41226138afc16c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b257b094b42b7b3d595dc593c44fe251451abb2e"
os = "windows"

    [[XGBoost.download]]
    sha256 = "9a012cbd5b1537d38957229b946ce2c30efce8da4ae049079d7079bb2214a17d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b973add4268f012e821144aa7d92afc6900f7951"
os = "windows"

    [[XGBoost.download]]
    sha256 = "ec0dfafe65a3385b713874478016a5a2d17d31f440347b5d3bf33ed00af0c63c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c741bbec9a8fb0d3a5bb3b2453f981768f37d0c"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a4592026daa0effff81b1133d392ab1c86f479d0456dfccb202b802142b15638"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "498a2346b881cf4d3dcfb7cc1151ce54050bbecc"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "39c8750afb3a51f1f08f242717777d6293d2837ed3a6329c1c4d3ff3f4e6321a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "949ecc663ad51053437ebf02bf8c4d442d4941d3"
os = "macos"

    [[XGBoost.download]]
    sha256 = "5ced40adb8d5dae45694aa9900d3c88a52a63398d770eb8cb26543dabd0ca07c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b1019c4b65ff2120c792d7f40be2600490fdb55"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "dd7fa86ec3c0fc64a53e171f94fbf86397b5ac087b68d0d272965eb5190c5a17"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8353ae0ef9d17e314c5379b77d7afa6031fdc6bf"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0f651cf85ff54bd12f6f2c1f9e155d961ec59ed3e96e6886f65f7ec81f93b2c5"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a663e7cca35dbc792da55baac00133fa0220767e"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b6c95d8b11f8293458e23d94560badc66e7ee671835cdf4aea856cd52522a383"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e1ac62618977933eecc3f796315577ea6235939"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2acc132b54f5d7201ed1c71a09da73f9c20d9a38b8475052e81e918119af9222"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "4fb5cd02db980c2ab6a5569407f21e39b373269a"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "231fefdea6363d201e218f57811a97b398098083ff2b3188f71c1f8ccbae28b6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde5ca269e2830965bbbf8f95c8b046707b1b259"
os = "windows"

    [[XGBoost.download]]
    sha256 = "2e127bc96ff78efcb7204296b833e369f51f8f14304155a35519133852fc8204"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c1811c53ee28d97495f630a6d2842377d7174e4"
os = "windows"

    [[XGBoost.download]]
    sha256 = "d6147f8bc3de9d6095baba9d4cd35f59010f802fa5f111ca3c4e43e843d3dd00"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.1+0/XGBoost.v1.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
