[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "3523ac68603d8e113e06e938a724ca14937b524c"
os = "macos"

    [[XGBoost.download]]
    sha256 = "ebd6b21a4439c5504c35cac522ae4fdd75ee49a65b2944009ad0de448a6a6ded"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65fae37403cd95b9322a372e6dce584edea77980"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "979d4cd07c485530460d5e34d3ae768a76d09249799b8f5cbb5d3921bc273088"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52d7e967635aad1b12ee5f7ac3593f843a1500f1"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0b379e284d018f29c852aad111dcb8642682e2df818e4e95890665eba23f25af"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89eee66bdf5a8512de24bf23066ae9a857ae79ff"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "139a8d79193c53cd01195283e2355da911cfacbdec820e644af2f7e4865a8acc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db49d332300dce7736631102a703b25718033a02"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b5e37e30a0decb11ed39d9b8b00da3cc1d12fe2ef475b574c0e53e6bf3b160a2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4942a1f590dc4337af1f2bc1689e5c8ab4271c37"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f706bf2bed35c99fec1e504360d85d009035c2aa82446f6dd74ef277a5024d3b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fbf1718294d29bccf9298e6edc4db634f548640"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b1b822424d6bfdbd2e5674de2f8dff6b762cad646a7da4502122845c32fde259"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da35a92448030dd7eeb298c47e65eda95ceea153"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "854d41d805091500d40c9435bd5c71d5a763ff73854b2228fe0a7822354f4960"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36206d2ff9b833a24931fef450bd87633d869754"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "60ec6699542b176d27ab32a73178551d223d385296363f30d48598bee8e4e699"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d2cfd04169b3133ad8016a7bcce561116f34f41"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "597f896238f5bea9489186a3ec4757ce23e02c564d15c43a08ffe716dfa4c45e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f29e493c0e0b818667b0bd7351e3e430c291902"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f59e82ac7940282b788cc12a67686bd6914652cf9fdb6c98f766f37808252fc4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a67008f5abce2fcbd7dd6cccab765f6ffd20fe"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e7e3e3ca58d3ac1c27e945526e7f8ef4b7aa1e039aae551b91df99f3fe17e0f1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b023023b605eb3cb4fd18e42e75f04e413aac9f0"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "70692c4d43003fc589b6214adfdf417a75b0f013047cf482708f5719c4aa916b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92ecac2da5c8c81e153e17ac221f07eab0f1819"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "14f37a8130c3153eb67ad86e0e2c0219af82d94c1232d9dd9d6c803344f94fe8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "870e2a0eae10608c005b45de1d835dbd9f721f60"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ecd6b14e4461880f20cad36a3708f2445579e768bc1b4d15409aa77f0e1247ba"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8da43168e2e761c39e560440ab7c0a461fc16830"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0e8689357e8d28c858757e95f4d87f2a5f6f15ee48609df80e5700268ec232ec"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63403d93c630a5e11ac14027571eb065895e9694"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c48c5a43f5233e683dc9806ab7b18a1f9cc992315c12315adfe44014d3821f7e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab754e0e2d354328f86245f67586ba476cfa2e9d"
os = "windows"

    [[XGBoost.download]]
    sha256 = "fea289f9e40bc8945a773bee27ffd50586d3b67ef650e414d6043e8b08f3720f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "459e86b346288c1a61925365cebffc7857a16839"
os = "windows"

    [[XGBoost.download]]
    sha256 = "7b869b169b4a7539ccc679a051f0eb8d0b9e38434f9325f6d233ecd0cee3a171"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b1b31ee10d2c4fb3398bfabf382d0fb4fa9f0e2"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a6de645c7f43b0e226c8c97cc4fdf79b41212081cbc1a19964a5d1a6faa2901d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2296b42fb043d699828b355448e04fc9f2e29842"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1ecd51f209b3a2691b987624800af484cf977ca824a3afa1e92513692d9fc8f7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "7b80e1ffd72294999be0cd3bcbb8a2e8fb225aec"
os = "macos"

    [[XGBoost.download]]
    sha256 = "a66d2472638caff41050d6befbc1586b01f0eccae50ddf3a2af57bc2db466e79"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8ccda2ce80d881cedcc143e31eb742bdeb64b1d"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b96d09933a60bdd6b6e756b5b8ffa880221dadaa3f192a8c5210980deb9c7eb3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8f655e21f07defffb7946a01b5bbbcb788f70d0"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cdefb44086eaecde1ef5c6b619ba324f40c64749b89fdff70358006e54584f69"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0eb88740eff5407af39b5c163e5ce421aa099a6"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2e243246560b81fb884bbbb138a7872256c4b3ede2f3768a99b3035a35d80950"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c5a62b3855140551e8da184ff6c25b9a3a4f5f6"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a03c616b114a69d381ce80a87e3419ffda375669a3c8cba4dfd9dd23b8f1bf04"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "e5001e7af027a7f46b704b851ff8f4bd5667223d"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "fa52d090e5bb37002dc9445b2580f6d0edb69c3440354bb7842de8a8da71d24f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecb3e5c54b82c2e2dc8e1087fc67b523e30e83b2"
os = "windows"

    [[XGBoost.download]]
    sha256 = "424f6fd28e7fa740d40552ff8368c1640b9512eb049cbd05a49afd1b3aa7561f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7265a6e3674130b6156ac709bfc2723dae88bae6"
os = "windows"

    [[XGBoost.download]]
    sha256 = "289ccb0dc8e85d2b2b97c056024d9392b1ec180ad212d97e208759a212dabd66"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.4.2+0/XGBoost.v1.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
