[[XGBoost]]
arch = "powerpc64le"
cuda = "none"
git-tree-sha1 = "8efc6ad069af330400a19777e6befc1f902d6ac5"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "d48d002bccce66deb22a603316f1263129c3540466612b0f85c565634ea9e140"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.powerpc64le-linux-gnu-cuda+none.tar.gz"
[[XGBoost]]
arch = "i686"
cuda = "none"
git-tree-sha1 = "5480c106342fac22244bdf68755df4e2640e59c6"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c5e4c1ca210b633e8a9accee63279ec355c785ce653ab4ea9aca1e1ba7e71388"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.i686-linux-gnu-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "0b12585240d379418043e3af3fc56fb3cdf4e5e2"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "fb16a6a5e4cea84006858d44efec1a3768662bf601930911e49a460b48f82e26"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-linux-gnu-cuda+none.tar.gz"
[[XGBoost]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "32d99127d62a0fd270697778c9ac16799f4205b3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5bac7df5001872738700a3e8c4f553b29afec0e51555e322dcd9645f99f25cb6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.aarch64-linux-gnu-cuda+none.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "83944c2f32ee79fea2d88d2251ae1a464424e997"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b675e577661a38802126c2f431e8541b8d50e7bb4fd5c49667a797b7a251c942"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.armv6l-linux-gnueabihf-cuda+none.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "c21b81896298341368adb71e7f5d43b377a269db"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "deafd8b098487685bb4861ff5fe762cc1b449373202d54cb5a1756d26c8c0594"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.armv7l-linux-gnueabihf-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "d33a6e5b25ca06c6d8ae799d7d0a7192fbf2f5b5"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "1d88d0dbe4fd6230b800812d9c30ee69d4c8b9d49d3eab867511cd6beda1b6d8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-apple-darwin-cuda+none.tar.gz"
[[XGBoost]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "e384296d1b27b8cace34414e78e034c1e045c8c2"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "3e4fabe40e917b12cd0e55e72affb6bad57364d05a6d6559f1811c1a63fd052f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.aarch64-apple-darwin-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "3c3ac2944ef8e676b9c9d65d25bc7d499f96d6b8"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "57f0f5f0eb03eaa816bde47ea7831d83bf658753c307ac94e51fb8a66575adc8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-unknown-freebsd-cuda+none.tar.gz"
[[XGBoost]]
arch = "i686"
cuda = "none"
git-tree-sha1 = "20df4797da55f4147baa1f6f6f7892205b56b619"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "31173d8aa3e24c31c7899b4f2f73ac227994ea001fe7b244301bc9e6def9ba1a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.i686-w64-mingw32-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "9dfc032fae8c47b2c94162ef5e3a40a8789d4824"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "49927984dbe856c56c05a5b7b0df3b2d9b90b2621d8b18f5502d1cbc9d150d56"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-w64-mingw32-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "a9be140705c190ad87628f0a950ecdc353b1d4f5"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1624cbde73325bcda7333430fed91c5e7692c16d3a8b906fde818f740f4a63b6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "91a7da72c5f3ba3c33512e44c6db27789d7540de"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "75139afc3b7ed6bcaef8e6027218813f132850369069cedcbc8b35c8323c060d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.5+0/XGBoost.v1.7.5.x86_64-linux-gnu-cuda+12.0.tar.gz"
