[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd8c65968d3f09be6903cb2e6fa394657a2e4702"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0e75737595308742a45237cbe6935ba2bca257e3f7c3624bddd80364082c7e4c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3949384751fda9e4b780d28350c2b8088a06a470"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "67cd68833b62e1a9edc5b385116acf6ccd28ab6c18ce014b977726a7c425f8d8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "577a26d424e95f4cd9accf030615eb49011d56ee"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3ebe94680eda453ed679df8b67a3f15b4a4e3fd125ca8f8ab69dca1322ae9b07"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e8a31596f06500c7621808047d569396901c1c8"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "00a91d97bed9b1059550b38c7e67589998c8604272bc4982683d6d3f6baa0803"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7783f316c8c1086646c70190ac08959aa335a54c"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a34416b3d4d87251808a84c9b56ed172940997f000610b9aa0a85691efbe801d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcce78cb9256bfe894ce2a3a562555ec6ad5baa7"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ebe684525f39b35b6aa0e44ece0b9d1154c9589b633bbd15ac171488d1f6f798"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "923967e2f5812f535a7400ec1c041cb285db0ed3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "aa1c32bfbb61a455ffcc5de00cb6fa553c9457800482a9555628ac8a066f996f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a945b24d0add86f0c793e3bc90f24e8ff4e57c0e"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0bd6bd54a66fb13cac25ad756b75a7d69601a09a901e90b990f46fde7a8c9b32"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfdf09ce832a971f318328eb5a439f72badfabaf"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "15e957b5e0b8afd22e36551d80cde044cb2cdebbcd8203209010443e658b502a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6242c93a7bb412cc812b073ba91525d2aeb6b04f"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "33f3de861bbb8309026438983ca4ee9f2d0747746003b39e9b97f4cce7b33411"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baf458958b5b1e50084e8e3732a3092025e1ee04"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8146338b54fe5d86df9ff2fe2b51fe0235ee531e171a0616bbde3669b52dbf82"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b55635be467ac9e2ca7a24db3521360bdd66222"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "11d3fb2d1722b2f4cd558963202bbf233b341706ca6d4e957a320a9aa3288658"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14f1c9a53d3ad07636d92de13fe3a69ea8b6e11f"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "93284f7065228d27052fab920399485097175c7fd266aee36ae9cdf96e6db256"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx03-cuda+none.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d0455597f6a9829e9d463eb984ee460e566fbb2"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b17608d1371ff38a11509cceed1a372e9a94e5a8a6403a30db416208fd9cfd3c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f256ef59b966461776a6ae56923c8c9cfc79f46"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ad97a44dcba0e1f6cf79e6c1b4ce304b417d8a3934e0251bc7c573f896cc1c1c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e7a715f1ef57d0dc51ffef786ce45d3f9820610"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "61ed9d3c673f0bcab45ed65637cd213d2b4cc6736a21f63188884084bc62a103"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ead9f4999041e2022c826bd68fc550d8ff8ffc28"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3dfa0097ebddcd25861cf6ae1b6077f6b636a6e8d252d9847441c22d8b994c6c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0e3723b08938bbb17c830b0504676f754149ab1"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b3ecf078ab346b72fdfe4152f504b04ec26f9c4a000b839e8b5c064747ea9dc4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6569188cab81567f0277d2f688c01699844e90e"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a10b79307c7e668f6ce41dff5beafde8de393516b66bbed0629f60f9ce2b65ef"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "560d0c6ec0e6670b00e852d5ab9e8d83f94b3169"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "df780b8043f32170e10473e88742e85ed41d1e1d0183f9e840dc70d9f5bc1387"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "cdc22a1b3a6d4624367b1d1142e4e8d708224f64"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "1ad6adefc9dfe2c5decd62cce06505dd59de46836011c8360975e23a9d59e6e7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "3f27b99e72fe96a5c6bef05538a7f919436e6b11"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "f1fe0274fb143aeb5df72504a81fb1c3878a2394eb75a8f3c76c69502af1d469"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "a9cdd768d552e4c1be6922a3dc81963fc7c61451"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "9d5261ec10d7408ed7dadd7d440098e4cfdad98526b1f605a01c10a7e2a258cc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4271fc904c90d01d7fc06bf3e6f7f06e72678f27"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "f3041077c05108ead1ea488de2c517aae21740dbe291a3ced69f0a72d42c7072"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f262aaa8d4cfe1d31d5f7610dd1c05791da341b3"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "9f971394f46f42292453f9a3f51cabdf68464710aefe8af6ceafc55a46151f52"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bf1cf2868fa567eefb1b9dcc4a304805d12eff7"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "6890833c66f54a9903ae1d8a6ccbb0ca8dec6523c8056305be5ed14a8745346d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b2b234ad1c350ae05b7f7455a74eb5e172293df"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "5f455dc419d777785e75b98acec52f72df5ef660aa122b11d2f2de0869d5c709"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20ccd855d0189e8615cc6e0f563b3deaca5db322"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "718944aa563d44ed4a46399e64ac6e58baf0247ccc5aea25b42b5ef3f07f8a65"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx03-cuda+11.4.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf2c9b1bd859d8533f4a6280058b5b4e2c21a8c4"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b05abf63272eb68242e7d4f99344ce59eae406934e50aa8e247671af028dd99e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx11-cuda+11.4.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b3b4209ef1bb7b4f5f0a3340a4d379becec0eaa"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3b644759fc73ea6118210e6913471ff7949181eb518e4010c48da6587d296f5c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx03-cuda+12.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "12.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f051efd4d9f45569cc348cbbb43db27e0394d232"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e1f720e769c03dcaf7da6fa58c0a0e1085fe0e911305c4058b52816fb0a7cb6a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v2.0.0+0/XGBoost.v2.0.0.x86_64-linux-gnu-cxx11-cuda+12.0.tar.gz"
