[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "ac3a6f3c3bbfb30e966fea707a29ccc48512e308"
os = "macos"

    [[XGBoost.download]]
    sha256 = "da070336b342c40835f8c9d4d62b9f657bcdc776934efcd83c083604a991ed11"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3564d137cb7f68100110d4082e352920aad44e6d"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3c37e230650b604688ce456d88e2e30580130f1713be603b02f3a5cf476cf910"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ced317e5da75435d54318b467f0d72bf6f104c41"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "99f789ece481eafa0564daa10183c24bd2db4de18b4c26d93461ec9371f8cec3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b120622460edd91f606d9202ea57552b73473b6"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bda905545ed3813a87dce1e1eafaf9daa6f359d3522c0c3fe79ce017c872b3b8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d2c02b3ae67843cc6d569ff34198388e1cfb038"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "48cfe80d9ed631575d218e4b2f93c10bd72cc7331a5bda9a7abd30914940d8d4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8644f6af4a4247cfd482154b9757ff5776f59e7a"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c04a5201f8a993a2ffcc07945574a86c5f963a66521ca8fedc2fa9d10b5f1158"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be24dc3624cdd6268d8305040e420b835028c695"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "187f237fdcc465e328a912943e1835321a7130c3b43a67da9b68e93a94547ff4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8501eee9faddd6396ac32afbca1c70e8a5965832"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6a5d26e79b0df5d73e7f288dfec73bdea0a5cf233e36592e239653da44324f97"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a09acadf9a74d6cae783608ffad0616fb12bf7b3"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f2d6fa7209faccc5687c02a3deb88a84413a219e8cb6a3c2659b5b29bc035708"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "257e283e9300861d1995ed5bcd3d851daefd555f"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bab8f7e257b7c14ad4c155bb4b9c45c0ba2f1f2b2a02fae028d83ae83b65b181"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fa3f22b0913eaf1203753cbdbcf50eb13bd9e2d"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "964faa2114cb82dd186b86875d0667093e4ddd3ee27d07e1f23f130e74fbbe4e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a5483d7c730e786149f9c2f3de50699d25d0aca"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "305791dc0f6eb1f203f21dba25977e0befb4bf5d5ed7a4d29f21a407851648dc"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e25a350fae8785aa1170431bfea1a3b896fa5db0"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "683f30b275ab4b1c8e41dae600166d8f32b22e63ea06919567140538c9aa7f42"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c0341daf59ec319d6e647ee2254b36fbdf2dd71"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e9c9a4f5f83a44bb776373e93e2555009e3e0d69cac6849a2eca27feb5d042fb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5957b840ab5baee9b07029c0e3854d92d029af6"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "744ba10b69c4c1300f6e12abddfd39efb114533ec973225fab9b24f792b427e1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "276df59fe8423a28726dc061a4225514702b55ef"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1cad160cc03fe41115bfb643f68987575b1f529619477089ce9aca417581df86"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29c51f54efdb6c329605b9d1c5d4175b9d6b53ba"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9a08d444dd63901c84a6b9e99e1f84fcf7bd9e95b8ae212f63067fd18287e2bb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "872b3018d8aa0d073541370acc1b9a4edc9355f6"
os = "windows"

    [[XGBoost.download]]
    sha256 = "eb0c5e50d4c806603ef42653ece43fd8e2363a90e56819dee6d4290a6cf7633a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09ae8e1401effa9edc3a701f560a88f01792429a"
os = "windows"

    [[XGBoost.download]]
    sha256 = "108288bfcd72b7e7cd0f248c41bc38ca1d65af47a62726b2ef146b98e668138f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6835c00c2128f4926f6fa45b64ebf50df960f5a1"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1cf32b0ad2589e098cd42fe31d5022be9ac31d72283f5db4ee793c94a351f563"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5031fcdda305ad2db447a1546f2d1fd079022046"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c4b8b16ee3c389602f40406588c993b877da815daad3f65cb98ddf27a4a1a3db"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "92495f2a0ff45af36ee1762e3c5720b7b0dba7e0"
os = "macos"

    [[XGBoost.download]]
    sha256 = "a504a008c838ae887a94bd94aa5e9bbb7248bb8b5442f89ad904fd443fa7945e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "008dee2a93bfc5869e2ac9ea96c21f3dac813141"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "7822aef8ab64914208f939238c0204d5fe20c3c028bd2217c6af029ec5aeeb51"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "501324fbf7eec8ade7ee93955843c5cbdbd43fdc"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "09667a932370f13ad9be4d946a28d329e3388ec4ce1cf7d51bb0a3eaee6a06e7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bba44b9e759d1e2905fa4ef96001cbb462a178e"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "3efe0afe3a13221c1bef2e723fe5b02cb98ec4c0d3696279654973ef08d4ac40"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e30a52726551f3caeb28a6f34ab38cad760cac6"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ff64c69e79738678c216f6cdd759ea2bfa3ccc969d4e77b928a1329a8f2d270f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "2087d8ee9835ac842592f7275d235fecba6fbe16"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "d7459de0a27bf07bfbde3d759dc416daaf3374a0caa2f8980d69327875a2a132"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "998f4c958380de2b7c91abf972305a375f7c6d12"
os = "windows"

    [[XGBoost.download]]
    sha256 = "0f90f4a95744c7524c63363c906cece7ee6f946a10bf1ccee2d4a98c2944dd69"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d880bc4d28708cf8759e145140b4a8e67de8ba2b"
os = "windows"

    [[XGBoost.download]]
    sha256 = "3a5265f6f9f5bf3ae859a2cc0fe11272d4db886567736737bbdbf9ee3b7892a1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.6.2+0/XGBoost.v1.6.2.x86_64-w64-mingw32-cxx11.tar.gz"
