[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "6f540752e02ea2d673e715fbdfe50eacae857179"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "a67a0b48acdcc4b13f07b8b03a79134142d0fe5eb5a414bfd3af91d24b7432c9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baeb41b9ff64006d5cefc677b10055f564af8862"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "db28cb4207d69ee8c2f5080f43e35e24316ba194d0c1e264419f4e598c1c30f3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8744eea926e2ba7410b216eb9a6d82ea321e6ff7"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "caf38afc1fa4896e634b5922849d829ca9888ed57d92b06a5cbb3f0231b5e252"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e0115a930c4486e9c11aa06b546f2301c8f4929"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "47e58b36b0f4d1a0488a67ec261ff8747e467af566231881208ffa17e0855b77"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "163b9ad5fc4960dc49904c380564b9f1198e7f37"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "34600eaec57243e47bf10ca413fffadd7bddf4e87dbcffdbfdc6825b4235ffa1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5706e931dd34ce514463d12ef7ec871153f47a37"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "10625ab3dc84d498889ae22c95cf18397571a4503520dcea411e8b8f46288c1e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c49810c70de3fc98ed259b5b3957b5a9f340ba0d"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5843fe44ef4c5a8661e43029928af1c70b0e41fc6c0830fc24664d8946c2cba1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf9ed912bc4fdcbb01af73864cf1d4eb184ad542"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a103b6c6354fdcc8c9e85db03f2187b69bf9f500a10ccfac674c747ca247f340"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd42accf4a01b31c797a6c1d3c1cd19ff51c3574"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "57a4a2aa35d3e58ba081ca0cab868c6a4202314640ce4359103e06fae9654d51"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b175ae3f8f3151e787edbc2fa4511491c9a86f97"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "6e18a71f46669c04f356e07d2d7ef60d1a00866cd2d1976db1d96ea10d41f1fa"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c796cf3bad544139214010388c39c087cef88419"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0bad631d6ab25036ec964f8b6a994688b8bbba595f68cfe80452dd3bee46bea0"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "874483f48fff68de59e965fbd532307256b60519"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bdf725c471e5623477b979e0b1b266656edaa1ef8b682301d72a0087af860986"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f85ddc7cceed84ba51d0d46c8e99598c4ba0308c"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "668aa905a588eb64089033179e3c8bc27eaf7c1a1aa10ff28d17a794c3691d36"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "686ea988f355191738f4c463a23e8b944695302b"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f59c4c9af9a4f59d98d0ce43e7293e825655cea45caa75635965505490bd4452"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b106f58f1e1201475b3c698a3946c714300e746"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1080068d9571857c17e29b50aa44ba3ee3b58ef511b9d72e297414ba85786ad9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cddb064fcd2d06a7e9409f5f9cfa4a143a7fcc71"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9887f81512c2e580b6b6f72621fc04c3f14aa95f7ffa80c0fce3e9d68542420e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91b8564dbe648d5db18c453ca505393df7062eee"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "47973ba420f3cd23bf2a44074bc06173a77a64b38d8b68ea819cfb941ddf3afb"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e94251f6fad5ec9e8b27680decb8ac9f9ecec64"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "15c9ec67de2deda1ed3d08cad8f217990a530da9449c13a5ea221dfd66cfae97"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fba52683354f3beefa75943a0fc84c9a53b6fd6"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "3a86ea2933c8a10eaafb78e2a04e46f3309d5b799f4987ae8bee0629ae13a89a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "115abcadf89c18479af41bcc0f87a09c8224bafb"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "fd53c6d51b4c8e972392749c6cd1f344ef92f2472d4bfbcd47dc12c2aa5c72f0"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6316e10934c48f226c38518c9ffdaa2914d260a3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "06cb4443becd5ee97111cccb7a2e6a5b88e7295857c103cd254c8047ef80ee25"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "ad04b96c642d07cdfb4edb156e621252591ca856"
lazy = true
os = "macos"

    [[XGBoost.download]]
    sha256 = "711539672fad7cf335b25975e2f7006bb503c08c6b6d3b2a2042cf1d244d6ed3"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba84a2ae00edb3e3a9332082baf3030b37933de2"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8c6c1cffcdfec6c61c33389c156124515e5004c935352c8d0e04ac6955a45162"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adf21769cad1c007e1bea4567dd759b91f37abf3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ac6c3f719c14afde7a2aea4236959e730c767056ece9f13524f91789d328acf2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-gnu-cxx03-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03b71821ee6a107e3842e3236a209e6428168fd3"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "f3afa42679ee6740ac530894c5876e3d6181ecd3b22c90bf580aedd34e4c9e40"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cuda = "11.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faebdd3657bd0a456b49b2ec077bc81bc10f7421"
lazy = true
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "30f671db140dfa6be3fcf43778627214e2a8dbf09f3d2eaa07d1a1977b805276"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-gnu-cxx11-cuda+11.0.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5889b15b7e830e36cb9f845b8671b6c02d994265"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1810134229f16339ac7d5068ae5a00918e183fad2f540a504d3610135f673250"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5fd630e0d44a4a593f8b76abbd0ac219f4400bb6"
lazy = true
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "21b399dd3c1f6427dd6faf0fefc987b1fbea7f95fa1c60f548e3b14733636086"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "97ac864275fd7b69276271e5d6f6107478d08713"
lazy = true
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "74d0620479aa4fc65e8138d544b1c935b3779364bd8a25cf149925926af2a405"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a58757f3ae68acbb76314e591ec485dcfa85dc47"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "482a16daad24b96b57e9ab49a554e03dde757da9b0b94874276cac44bd6f02d2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45d1df01f8025cf761017f8932758d5d0e22a835"
lazy = true
os = "windows"

    [[XGBoost.download]]
    sha256 = "7b7c99464ec53380518c399ebdf92c0ba40d01f6fd86eade10bfefe0d2a22479"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.7.3+0/XGBoost.v1.7.3.x86_64-w64-mingw32-cxx11.tar.gz"
