[[XGBoost]]
arch = "aarch64"
git-tree-sha1 = "79460e7346b8e71372d1bdb53bf18a9503cf49c2"
os = "macos"

    [[XGBoost.download]]
    sha256 = "790f3caaf3b0d8b40ddc7faaf1780490764456feadcffadbdf3b6b433b22161f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.aarch64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f2ed52484e1d917da8b19bfccff683191f427e"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e1933bff2f2ea243beaa2d87268c4fb3a6b0dfeed12516fe3ae172bac6eb53a7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57a0c04e6454ae6452343d615ad8d29490ea0d62"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cc1604022bd45323f534fd8002d700c1a967729ee8316e136dbe7d5e3f565853"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05c3badcae581701079ac3b2ad3163d028df3bcf"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "e2c7b5fd8ef39a23882044763aeff0ed0213f87cb05759ef8c8a9a71b5e32b7a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e49336aa5a49a41eeb1a654fcc99e0f2b14e1d2c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "5e0e5ced01ca1f38036487fef8360224b0ced34b45954704224a60fad66838e7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe02ca72d2a56a89ecebd61da8d9749ffb01c299"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2e712798e1712f39282eeea12854a691623460d7b61fb22ee46e38b2094f422b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a117ecd3ada1a02b244526de93194c9594d2a3c9"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "918813dd794e2b5a49f53eef942923efffce5f8f416de8dc371fe98aa605d84d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bf5624de7bb3cfe30952e0b97f93205672b61f7"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "43533a4f569854b7083bd7f075057d6076f08ccfb7041b0ecf32201e2228aa39"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7d3963f9a760420954cc2eea7100f3f3e05d4c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "9752d9d1ae37f11ca51e6e31cd959c06525f099dc70d2e72cb0483e2b8e3531e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61e791f40d04934331bb3e41b2985ee050abab64"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ae16f1139225b48bcb2b5116f7f8d1029988fcf93766536cc2322a8989569801"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9d1dc0975ba3299ae678f608ff77369f7c0f23c"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0c026e92f8617067deb48421730b1d69c4942f152be41427f67814a7dd3d513e"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ed9250ad97e71fa4bda2562b69e439d73178533"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "84ed8363e9a5796ef04a9800066b31f18aaa8c0999309bf4215914a78fe7c43b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93db7fda67ad375b98658b7042cb1fa2d3ed850f"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "997a477bd647b2e6f0b9597513abb911048b06b4b5ccc8ae3c88da7d240ac945"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9566ec9fbcb835e6c671f757c06fb07ef124495d"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ea8a60a3148bcf6c28061df88a34525cdb6c73831878a99c8865932278075206"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c6ff22ba6104448bd81cc9f0ee848d5bd363a57"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "302595de9ba38a38c4d10db0d0e0d14541c0f655469df37300bf9bd503c9ad8d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46c8d62568429ec3e244bd7e6f790c782ef589fb"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2a93c81ed47c74baf0b6a2c50291709d7bcc7f666cbb7977098970b06a432ce1"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e844a1ce5096baddf0eb398a967abab37895b2c"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "c62895f62a394256ed46235551e21bb696f462b2a7aa7710651cd97c2730a458"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a99c66ae10bb465829ea839e0ea87f1016533f64"
os = "windows"

    [[XGBoost.download]]
    sha256 = "3855b2be82d38dcbf4a2ef12138ccb3c90e88d409ff70faf1179b72345b435d9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4103fa5110283671c3bc570027b4790cfb788807"
os = "windows"

    [[XGBoost.download]]
    sha256 = "116a32db5bee6c683eb4039982b76f0fb660f1842416ebda1e747a7be98f70c7"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9efd21a2404d600133121ca95a1de07f7216646"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "1ae42c584bc950aea6a29c6566053c62646c1036aab932393da300faf6c40aa9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "663de05987cf0738f0a16e6aaf3d609ee647409b"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ee7cf06ffe9a1f83b902b9c5df7e697429c24cbc8bc37b26c8af3b7c73998615"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "a019695f068ea21ace48ff0e473583a36060241a"
os = "macos"

    [[XGBoost.download]]
    sha256 = "729eda6234f58608fed972c56714f645519a88cd831347dba1de69a71e35a337"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-apple-darwin.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "113c908052bf29e797f1653390d625a97fb3f2de"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "0b1e89c96a78bb4b5bdb89367e9d068201fa1e0e5e373ebc4a0d71b6e5881f17"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cec180bd4d0d5762169f7d2a1f732c946fca492e"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "b5fdd62f3b4145d5668b67ea2725f3c8bc2b25b0609716716cacbb159d10210a"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d07d8c48bfe9a7010c2ef361b5f0ec1228c3ccb4"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a14b5d1418dc599d236b41d2280096f9d0af4671fea5cab1b2fddc1dba82cbf2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68bf25ad6b16c52eca868bbe6d42b4c4aed81c71"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "481f30a760b663e499264bc631aa11f7544a2fa940af16495ec06d6eae9778f6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
git-tree-sha1 = "9887a15ec5c7955974797b4a9df312ff2821ad1c"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "26b6028aede7e75c00ac32ac2e6032d269bbb50852e86d748c3ed5170a13054b"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f385337fcb7c41c4e9d5ec70b9572fd9e87544e5"
os = "windows"

    [[XGBoost.download]]
    sha256 = "fd04f227040f7cea99cf89f2f3f0e8de74772bd66f68403d668cb0d4b8c994f8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "976605773c83686d53793313785cc9e943ca9bd2"
os = "windows"

    [[XGBoost.download]]
    sha256 = "bbc09f79c4680d2b9ec1d884be5ddb8eff4c7a4f457fbff6d65cf6aee7a903ba"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.5.2+0/XGBoost.v1.5.2.x86_64-w64-mingw32-cxx11.tar.gz"
