[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbba9afaa2b20a24de5d7891c6127d6439647b23"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "5ab0f75327cb189666dcfff3d9836eb32b6ffba51cbee1251b2d2778c57fc2ec"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6af25f2569d0221f9e2ddc70c5601f21a40e50f"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "2fc1adf6075e6c1aa99da0d65eb3b87cbcbfce6799d569895d8ce6ae0fd203e8"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "571b46725a50290b9917bb60d3e7c9126d741667"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8ffa3ad644a5254ffb157c0990dd98fb868b45770ea102d146c448774563ec85"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d264680fb494ac041da9ad71830cb14ae0a80ce"
os = "windows"

    [[XGBoost.download]]
    sha256 = "38ff065b38f17631a6f08a39916fe5caa93606d284b6c0eb75a17a8041073fd9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "546ce37d131f629e3e4fc25635e8bdc05e315a6b"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "79c39c98eb07cd2f1415304b2be77f43dc0396ae841a4ecfdff2d695f902f4fa"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31b470922d2b3af70653fdef43d760195a690fe6"
os = "windows"

    [[XGBoost.download]]
    sha256 = "c63db3cc6679c92648c1809ecbae749aafb2cc234959aed51332a69a622c7b74"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37a46288287821f86329e8f4d25130918513fe9b"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "cfd54f412b24c09695c4d0d8e95594fb2026c5029c7d5076aae3627d70c65266"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "926ad47b4034f036e5c3dad05a5ec690e37c22bb"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "932c95120df43bcd6b932304ba5797f72d373af9fcf82bfca1c44f54c2ffcefd"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a38089c467d0be175121ce03a707f0782f1424ee"
os = "windows"

    [[XGBoost.download]]
    sha256 = "0d9bbcf1c1c8e4a78f607a8d192c00ef9f7c62fd83d6b75e6e65131c321e3f5c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04bba2a31383df46e2ab07bea334c7bdccb4b66d"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8694269e3bcb6ba0268870542682081497e0549a50bcfb9e1c15e318b702416d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1833c1e2408b5514cb33f256cf4485a8ec7c640f"
os = "freebsd"

    [[XGBoost.download]]
    sha256 = "213b25fa2412c902e68838ef8654f02d0c649fbd30d30669aa9f4ea9c3633166"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e249348acc75859c878fcb7e5fe999dcee7ea475"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4159e482024a811be48d574d7590ab07873bb73e981c0f3e6a11499712fb465c"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb3765906894d31ec485cf7126f99bfd2a6143de"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "594a87d2c55f6b0699144ae76a3c48da9b519ea8a5c125be4abd543ccaabedd9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bd6a9e3be496f4bebfd74e83448205cf2135473"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "42f19a7daa62eab296e82759cd2bbbf8711757e8da92e137c4fba3f03d1f648f"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ede3b64dc82a947b72a75f6f8fbb6f8708a1e19"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "bdbfff58bae2092276a6cf06a5ed1c8609a03bbee09d5c0ccc0c25d7b9b750c9"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e128f3d4f5c30078bb17006b6ecc13c6f02b41ad"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "4c65a2a351f64ac7b383a346145017c7f20d1c775b68af66e054a3f0255a25e4"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35d3301278c69821edd989ff250350d787dc7e10"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "a26b61913ace5c066e6cb30e0e9214ee3de20036350081d09ea4f03a31f4f6d2"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-linux-musl-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "278858479be27d5d3b9662fa4fb097c525431732"
os = "windows"

    [[XGBoost.download]]
    sha256 = "d9a06c5584f642df7460e10d5b950c15fd2fb33f310d5c428b135a579c0b3713"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69999bb0c06b80809233551b1cda371354e655f6"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "8b87c9c93b8c5537be93a3396a4c28ba76f83a80aff5831d60e336a8134d9c2d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1bdc0d83d5c30113676e43491bb817f40595e56"
os = "macos"

    [[XGBoost.download]]
    sha256 = "e4577205b30be0161030b380a65a22b6a3c737cf60fabc0477f750483bf525ef"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[XGBoost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b88d419277d20b58e3d278a266bb4b662b5dcbec"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "af4b6b35bb378f46709b32392dbef61e2bf15ac8ae9c977e671f29c4e2f78d2d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.i686-linux-gnu-cxx03.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "643cbc9f0c355f22091ecf7b93cdd8cce5b6bfcb"
libc = "musl"
os = "linux"

    [[XGBoost.download]]
    sha256 = "124773a4395cabd05da964d404cbaaaf9296ce5ddd93fdc3456782a32c415c8d"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[XGBoost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "096c4b56c8fda0c5daddd8eab61f938dafdfb6f3"
os = "macos"

    [[XGBoost.download]]
    sha256 = "628c02ce731c9096a1f124614c06a9b2529e13f4d89e8d96988531cadda3adb6"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[XGBoost]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b74f307f3830c77e6ad13fb17e05a9c2174d15a"
libc = "glibc"
os = "linux"

    [[XGBoost.download]]
    sha256 = "ce3bfd508068d34ee84f144920a61cf6aa5068498acc527f8eca66908f50e879"
    url = "https://github.com/JuliaBinaryWrappers/XGBoost_jll.jl/releases/download/XGBoost-v1.1.0+0/XGBoost.v1.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
